<?php
Route::post('/message/send','MessageController@sendMessage');
Route::get('/message/getMessages/{page}/{size}/{UserId}','MessageController@getUserMessages');
Route::get('/message/checkMessage/{MId}','MessageController@checkUserMessage');
Route::get('/message/getUnreadMessages/{page}/{size}/{UserId}','MessageController@getUserUnreadMessages');
Route::get('/message/getUnreadMessageCount/{userId}','MessageController@getUserUnreadMessageCount');
Route::get('/message/getMessageCount/{userId}','MessageController@getUserMessageCount');
Route::get('/message/deleteOwnMessage/{userId}/{MId}','MessageController@deleteOwnMessage');
Route::post('/message/deleteOwnMessage/{operatorId}/{userId}/{MId}','MessageController@deleteOwnMessage');